name: ReachChecker
version: @version@
main: xyz.n7mn.dev.reachchecker.ReachChecker
authors: [ 7mi_chan ]
description: ReachChecker
commands:
  alerts:
    usage: '/alerts'
    description: ''
  look-up:
    usage: '/look-up {PLAYER-ID}'
    description: ''