name: ReachChecker
version: @version@
main: xyz.n7mn.dev.reachchecker.ReachChecker
authors: [ 7mi_chan ]
description: ReachChecker
commands:
  alerts:
    usage: '/alerts'
    permission: "reachchecker.alert"
    description: ''
  look-up:
    usage: '/look-up {PLAYER-ID}'
    permission: "reachchecker.lookup"
    description: ''
  cps:
    usage: '/CPS {PLAYER-ID}'
    permission: "reachchecker.cps"
    description: ''