name: ReachChecker
version: @version@
main: xyz.n7mn.dev.reachchecker.ReachChecker
authors: [7mi_chan, Kouta1212, 128bytes(PerfectBoat)]
description: ReachChecker
commands:
  alerts:
    usage: '/alerts'
    permission: "reachchecker.alert"
    description: ''